
    % INPUT
    %dir: directory containing images
    % filename1: the first image
    % filename2: the second image 
    % preprocess_setting: cell of dimension 10 x 2
    % piv_setting: cell of dimension 13 x 2
    % nr_of_cores: number of cores specified by user 
    % graph: bool, whether to display graphical output ( not available
    % for parallel worker)
    
    % OUTPUT
    % x, y: coordinates of vectors
    % u, v: resulted components of vector field
    % typevec: type vector
    % corr_map: corellation map

image1=imread('./image1/gk2a_ami_le2_sst_ko020lc_202405122100.png');
image2=imread('./image1/gk2a_ami_le2_sst_ko020lc_202405122110.png');

    %%  
    %{
    image1 = PIVlab_preproc (image1,...
        preprocess_setting{1,2},...
        preprocess_setting{2,2},...
        preprocess_setting{3,2},...
        preprocess_setting{4,2},...
        preprocess_setting{5,2},...
        preprocess_setting{6,2},...
        preprocess_setting{7,2},...
        preprocess_setting{8,2},...
        preprocess_setting{9,2},...
        preprocess_setting{10,2}); %preprocess images
    image2 = PIVlab_preproc (image2,...
        preprocess_setting{1,2},...
        preprocess_setting{2,2},...
        preprocess_setting{3,2},...
        preprocess_setting{4,2},...
        preprocess_setting{5,2},...
        preprocess_setting{6,2},...
        preprocess_setting{7,2},...
        preprocess_setting{8,2},...
        preprocess_setting{9,2},...
        preprocess_setting{10,2});
%}
    %% Setting Parameters

piv_setting = cell(15, 2);

% Pass1의 Interrogation area (ex. 32x32 pixels)
piv_setting{1, 2} = 64;

% Step size (ex. 16 pixels)
piv_setting{2, 2} = 32;

piv_setting{3, 2} = 1; % Sub-pixel method , 1 : Gaussian,   2: 2D-Gaussian
piv_setting{4, 2} = []; % Mask (ex. no mask or use a specific mask)
piv_setting{5, 2} = []; % ROI (ex. [x, y, width, height])

% Pass 개수 설정
piv_setting{6, 2} = 4;

% Pass2 area 설정
piv_setting{7, 2} = 48;

% Pass3 area 설정
piv_setting{8, 2} = 32;

% Pass4 area 설정
piv_setting{9, 2} = 24;

piv_setting{10, 2} = '*linear';
piv_setting{11, 2} = 0; % reapeat
piv_setting{12, 2} = 0; % mask auto
piv_setting{13, 2} = 0; % do_linear_correlation

piv_setting{14, 2} = 1; % repeat last pass
piv_setting{15, 2} = 0.025; % repeat last pass until quailty slope



    %%

    [x, y, u, v, typevec,corr_map,~] = piv_FFTmulti(image1,image2,...
        piv_setting{1,2},...
        piv_setting{2,2},...
        piv_setting{3,2},...
        piv_setting{4,2},...
        piv_setting{5,2},...
        piv_setting{6,2},...
        piv_setting{7,2},...
        piv_setting{8,2},...
        piv_setting{9,2},...
        piv_setting{10,2},...
        piv_setting{11,2},...
        piv_setting{12,2},...
        piv_setting{13,2},0,...
				piv_setting{14,2},...
				piv_setting{15,2}); %actual PIV analysis
        

        
      imagesc(double(image1)+double(image2));colormap('gray');
      hold on
      quiver(x,y,u,v,'g','AutoScaleFactor', 1.5);
      hold off;
      axis image;
      set(gca,'xtick',[],'ytick',[])
      drawnow;
        
